#bare minimum hostfile

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=openshift-enterprise
openshift_release=3.9

openshift_disable_check=memory_availability,disk_availability,docker_image_availability

# Debug level for all OpenShift components (Defaults to 2)
debug_level=2

openshift_master_default_subdomain=apps.pk.com

system_images_registry="registry.access.redhat.com"

# Manage openshift example imagestreams and templates during install and upgrade
openshift_install_examples=true

# htpasswd auth
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

[masters]
master.pk.com

[etcd]
master.pk.com

[nodes]
master.pk.com openshift_hostname=master.pk.com
node-1.pk.com openshift_hostname=node-1.pk.com openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
node-2.pk.com openshift_hostname=node-2.pk.com openshift_node_labels="{'region': 'primary', 'zone': 'default'}"
infra-1.pk.com openshift_hostname=infra-1.pk.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
infra-2.pk.com openshift_hostname=infra-2.pk.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
